# Render Blueprint for Dristhi backend (FastAPI) + managed Postgres + Redis

services:
  - type: web
    name: dristhi-backend-311
    runtime: python
    plan: free
    rootDir: backend
    region: oregon
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: bash ./entrypoint.sh
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: PYTHONPATH
        value: .
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DATABASE_URL
        fromDatabase:
          name: dristhi-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: dristhi-redis
          type: redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "60"
      - key: API_V1_STR
        value: /api/v1
      - key: ENABLE_AI_FEATURES
        value: "false"
      # CORS: Add your Vercel domain(s) below, comma-separated (no trailing slash)
      # Example: https://dristhi-demo.vercel.app,https://your-custom-domain.com
      - key: BACKEND_CORS_ORIGINS
        value: https://<your-vercel-project>.vercel.app
      # Optional: dynamic CORS for debugging only (do not enable in prod)
      - key: ALLOW_CORS_FROM_REQUEST
        value: "0"

  - type: redis
    name: dristhi-redis
    plan: free
    ipAllowList: []

  - type: postgres
    name: dristhi-postgres
    plan: free
    ipAllowList: []
    databaseName: dristhi
    user: dristhi
